name: Tests

on:
    push:
      branches: 
        - master
    pull_request:
      branches:
        - master


jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: node:13.4.0

    steps:
    - uses: actions/checkout@v1
    - name: Install modules
      run: npm i
    - name: Run tests
      run: npm run test
      